export const LOGIN = "LOGIN";
export const FETCHPOSTS = "FETCHPOSTS";
export const FETCHCOMMENTS = "FETCHCOMMENTS";
export const FETCHOPPORTUNITIES = "FETCHOPPORTUNITIES";
export const GETUSERS = "GETUSERS";
